type: depth_anything_v2
name: depth_anything_v2_vit_b-r20240721
provider: HKU
display_name: Depth Anything V2 (ViT-Base)
model_path: models/depth_anything_v2_vitb.onnx
render_mode: color  # 'color' or 'gray'