type: sam_med2d
name: sam_med2d_vit_b-r20230901
provider: OpenGVLab
display_name: SAM-Med2D-256x (ViT-Base)
encoder_model_path: models/sam-med2d_b.encoder.onnx
decoder_model_path: models/sam-med2d_b.decoder.onnx
input_size: 256
