type: yoloe
name: yoloe_v8l-r20250524
provider: THU
display_name: YOLOE-v8-L
model_path: models/yoloe-v8l-seg.pt
model_pf_path: models/yoloe-v8l-seg-pf.pt
embedding_model_path: models/mobileclip_blt.pt
input_height: 640
input_width: 640
iou_threshold: 0.70
conf_threshold: 0.25
max_det: 1000
with_mask: false